name: curs_flutter
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  assets_audio_player: ^3.0.4+1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  very_good_analysis: ^2.4.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/sound/
  uses-material-design: true

